# Generated by Django 4.0.3 on 2022-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionalternative',
            name='useralternative',
            field=models.CharField(max_length=3),
        ),
    ]
